{
 "title": "Scala 2 to Scala 3 Course",
 "description": "Sudoku Solver Telemetry",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Akka System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unhandled Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(akka_system_unhandled_messages_total)"
    }
   ]
  },
  {
   "title": "Dead Letters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(akka_system_dead_letters_total)"
    }
   ]
  },
  {
   "title": "Actor Processing Time Seconds Sum",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(akka_actor_processing_time_seconds_sum[$__rate_interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Actor Mailbox Size Bucket",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(akka_actor_mailbox_size_bucket[$__rate_interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "System Unhandled Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(akka_system_unhandled_messages_total[$__rate_interval])",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(irate(akka_actor_errors_total[$__interval]))"
    }
   ]
  },
  {
   "title": "System Dead Letters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(akka_system_dead_letters_total[$__rate_interval])",
     "legendFormat": "{{system}}"
    }
   ]
  }
 ]
}