{
 "title": "Scala 2 to Scala 3 Course",
 "description": "Sudoku Solver Telemetry",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sytem Processed Messages Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(akka_system_processed_messages_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Active Actors Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(akka_system_active_actors_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Unhandled Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(akka_system_unhandled_messages_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Dead Letters",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(akka_system_dead_letters_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processing Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Actor Processing Time Seconds Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(akka_actor_processing_time_seconds_bucket[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Actor Processing Time Seconds Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(akka_actor_processing_time_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actor Processing Time Seconds Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(akka_actor_processing_time_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Mailbox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Actor Mailbox Size Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(akka_actor_mailbox_size_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actor Time in Mailbox Seconds Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(akka_actor_time_in_mailbox_seconds_bucket{job=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actor Mailbox Size Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(akka_actor_mailbox_size_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actor Time in Mailbox Seconds Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate(akka_actor_time_in_mailbox_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actor Mailbox Size Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(akka_actor_mailbox_size_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actor Time In Mailbox Seconds Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "akka_actor_time_in_mailbox_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}