version: '3.9'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
    external: false
  grafana_data:
    external: false
  grafana_log:
    external: false

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.0.3
    volumes:
      - ./infrastructure/grafana/etc:/etc/grafana:ro
      - grafana_data:/var/lib/grafana
      - grafana_log:/var/log/grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
    privileged: true
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.46.0
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    privileged: true
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
